name: itcores_internship_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  go_router: ^14.6.1
  get_it: ^8.0.2
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  flutter_localization: ^0.2.2
  flutter_expandable_fab: ^2.3.0
  dotted_border: ^2.1.0
  
  flutter_localizations:
    sdk: flutter
  intl: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  
  assets: 
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100